-- Auto-generated from supabase/seeds/external_source_game_mappings.csv.
-- Do not edit this file directly; update the CSV and re-run:
--   ./scripts/generate-external-source-mappings-seed.sh
--
-- Idempotent seed for external provider handle -> PatchNotes game mappings.

begin;

create temporary table seed_external_source_game_mappings (
  source_provider text not null,
  source_handle text not null,
  game_title text not null,
  match_priority integer not null,
  is_active boolean not null
) on commit drop;

insert into seed_external_source_game_mappings (
  source_provider,
  source_handle,
  game_title,
  match_priority,
  is_active
)
values
  ('twitterapi.io', 'marathonthegame', 'Marathon', 10, true),
  ('twitterapi.io', 'oldschoolrs', 'Old School RuneScape', 10, true),
  ('twitterapi.io', 'pragmatagame', 'Pragmata', 10, true),
  ('twitterapi.io', 'pragmata_jp', 'Pragmata', 20, true);

do $$
declare
  v_missing_games text;
begin
  with missing_games as (
    select distinct s.game_title
    from seed_external_source_game_mappings s
    left join public.games g
      on lower(g.title) = lower(s.game_title)
    where g.id is null
  )
  select string_agg(game_title, ', ' order by game_title)
  into v_missing_games
  from missing_games;

  if v_missing_games is not null then
    raise exception 'external_source_game_mappings seed aborted: missing games in public.games -> %', v_missing_games;
  end if;
end;
$$;

with seed_rows as (
  select
    lower(source_provider) as source_provider,
    lower(source_handle) as source_handle,
    game_title,
    match_priority,
    is_active
  from seed_external_source_game_mappings
),
resolved as (
  select
    s.source_provider,
    s.source_handle,
    g.id as game_id,
    s.match_priority,
    s.is_active
  from seed_rows s
  join public.games g
    on lower(g.title) = lower(s.game_title)
),
updated as (
  update public.external_source_game_mappings m
  set
    source_provider = r.source_provider,
    source_handle = r.source_handle,
    game_id = r.game_id,
    match_priority = r.match_priority,
    is_active = r.is_active,
    updated_at = now()
  from resolved r
  where lower(m.source_provider) = r.source_provider
    and lower(m.source_handle) = r.source_handle
    and (
      lower(m.source_provider) is distinct from r.source_provider
      or lower(m.source_handle) is distinct from r.source_handle
      or m.game_id is distinct from r.game_id
      or m.match_priority is distinct from r.match_priority
      or m.is_active is distinct from r.is_active
    )
  returning lower(m.source_provider) as source_provider, lower(m.source_handle) as source_handle
)
insert into public.external_source_game_mappings (
  source_provider,
  source_handle,
  game_id,
  match_priority,
  is_active
)
select
  r.source_provider,
  r.source_handle,
  r.game_id,
  r.match_priority,
  r.is_active
from resolved r
left join updated u
  on u.source_provider = r.source_provider
 and u.source_handle = r.source_handle
where u.source_provider is null
  and not exists (
    select 1
    from public.external_source_game_mappings m
    where lower(m.source_provider) = r.source_provider
      and lower(m.source_handle) = r.source_handle
  );

-- Snapshot current mappings after apply.
select
  m.source_provider,
  m.source_handle,
  g.title as game_title,
  m.match_priority,
  m.is_active,
  m.created_at,
  m.updated_at
from public.external_source_game_mappings m
join public.games g on g.id = m.game_id
order by lower(m.source_provider), lower(m.source_handle);

commit;
