#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_CSV_FILE="$ROOT_DIR/supabase/seeds/external_source_game_mappings.csv"
DEFAULT_SQL_FILE="$ROOT_DIR/supabase/seeds/external_source_game_mappings.sql"
CSV_FILE="${1:-$DEFAULT_CSV_FILE}"
SQL_FILE="${2:-$DEFAULT_SQL_FILE}"

if [[ ! -f "$CSV_FILE" ]]; then
  echo "Seed CSV file not found: $CSV_FILE" >&2
  echo "Usage: ./scripts/generate-external-source-mappings-seed.sh [path/to/csv_file.csv] [path/to/output_seed.sql]" >&2
  exit 1
fi

if command -v python3 >/dev/null 2>&1; then
  PYTHON_BIN="python3"
elif command -v python >/dev/null 2>&1; then
  PYTHON_BIN="python"
else
  echo "Python is required to generate seed SQL (python3 preferred)." >&2
  exit 1
fi

mkdir -p "$(dirname "$SQL_FILE")"
TMP_SQL="$(mktemp "${TMPDIR:-/tmp}/external_source_game_mappings.XXXXXX.sql")"
cleanup() {
  rm -f "$TMP_SQL"
}
trap cleanup EXIT

"$PYTHON_BIN" - "$CSV_FILE" "$TMP_SQL" <<'PY'
import csv
import sys
from pathlib import Path

csv_path = Path(sys.argv[1])
sql_path = Path(sys.argv[2])

required_columns = [
    "source_provider",
    "source_handle",
    "game_title",
    "match_priority",
    "is_active",
]


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def parse_bool(raw_value: str, line_no: int) -> str:
    value = raw_value.strip().lower()
    if value in {"true", "t", "1", "yes", "y"}:
        return "true"
    if value in {"false", "f", "0", "no", "n"}:
        return "false"
    raise ValueError(f"line {line_no}: invalid is_active '{raw_value}' (expected true/false)")


rows = []
with csv_path.open(newline="", encoding="utf-8") as handle:
    reader = csv.DictReader(handle)
    headers = reader.fieldnames or []
    missing = [column for column in required_columns if column not in headers]
    if missing:
        raise ValueError(f"missing required CSV columns: {', '.join(missing)}")

    for line_no, row in enumerate(reader, start=2):
        values = {column: (row.get(column) or "").strip() for column in required_columns}
        if not any(values.values()):
            continue

        source_provider = values["source_provider"].lower()
        source_handle = values["source_handle"].lower()
        game_title = values["game_title"]

        if not source_provider:
            raise ValueError(f"line {line_no}: source_provider is required")
        if not source_handle:
            raise ValueError(f"line {line_no}: source_handle is required")
        if not game_title:
            raise ValueError(f"line {line_no}: game_title is required")

        try:
            match_priority = int(values["match_priority"])
        except ValueError as exc:
            raise ValueError(
                f"line {line_no}: match_priority '{values['match_priority']}' is not a valid integer"
            ) from exc

        if match_priority < 0:
            raise ValueError(f"line {line_no}: match_priority must be >= 0")

        is_active = parse_bool(values["is_active"], line_no)
        rows.append((source_provider, source_handle, game_title, match_priority, is_active))

if not rows:
    raise ValueError("no valid seed rows found in CSV")

value_lines = []
for index, (source_provider, source_handle, game_title, match_priority, is_active) in enumerate(rows):
    suffix = "," if index < len(rows) - 1 else ""
    value_lines.append(
        f"  ({sql_quote(source_provider)}, {sql_quote(source_handle)}, "
        f"{sql_quote(game_title)}, {match_priority}, {is_active}){suffix}"
    )

values_block = "\n".join(value_lines)

sql = f"""-- Auto-generated from supabase/seeds/external_source_game_mappings.csv.
-- Do not edit this file directly; update the CSV and re-run:
--   ./scripts/generate-external-source-mappings-seed.sh
--
-- Idempotent seed for external provider handle -> PatchNotes game mappings.

begin;

create temporary table seed_external_source_game_mappings (
  source_provider text not null,
  source_handle text not null,
  game_title text not null,
  match_priority integer not null,
  is_active boolean not null
) on commit drop;

insert into seed_external_source_game_mappings (
  source_provider,
  source_handle,
  game_title,
  match_priority,
  is_active
)
values
{values_block};

do $$
declare
  v_missing_games text;
begin
  with missing_games as (
    select distinct s.game_title
    from seed_external_source_game_mappings s
    left join public.games g
      on lower(g.title) = lower(s.game_title)
    where g.id is null
  )
  select string_agg(game_title, ', ' order by game_title)
  into v_missing_games
  from missing_games;

  if v_missing_games is not null then
    raise exception 'external_source_game_mappings seed aborted: missing games in public.games -> %', v_missing_games;
  end if;
end;
$$;

with seed_rows as (
  select
    lower(source_provider) as source_provider,
    lower(source_handle) as source_handle,
    game_title,
    match_priority,
    is_active
  from seed_external_source_game_mappings
),
resolved as (
  select
    s.source_provider,
    s.source_handle,
    g.id as game_id,
    s.match_priority,
    s.is_active
  from seed_rows s
  join public.games g
    on lower(g.title) = lower(s.game_title)
),
updated as (
  update public.external_source_game_mappings m
  set
    source_provider = r.source_provider,
    source_handle = r.source_handle,
    game_id = r.game_id,
    match_priority = r.match_priority,
    is_active = r.is_active,
    updated_at = now()
  from resolved r
  where lower(m.source_provider) = r.source_provider
    and lower(m.source_handle) = r.source_handle
    and (
      lower(m.source_provider) is distinct from r.source_provider
      or lower(m.source_handle) is distinct from r.source_handle
      or m.game_id is distinct from r.game_id
      or m.match_priority is distinct from r.match_priority
      or m.is_active is distinct from r.is_active
    )
  returning lower(m.source_provider) as source_provider, lower(m.source_handle) as source_handle
)
insert into public.external_source_game_mappings (
  source_provider,
  source_handle,
  game_id,
  match_priority,
  is_active
)
select
  r.source_provider,
  r.source_handle,
  r.game_id,
  r.match_priority,
  r.is_active
from resolved r
left join updated u
  on u.source_provider = r.source_provider
 and u.source_handle = r.source_handle
where u.source_provider is null
  and not exists (
    select 1
    from public.external_source_game_mappings m
    where lower(m.source_provider) = r.source_provider
      and lower(m.source_handle) = r.source_handle
  );

-- Snapshot current mappings after apply.
select
  m.source_provider,
  m.source_handle,
  g.title as game_title,
  m.match_priority,
  m.is_active,
  m.created_at,
  m.updated_at
from public.external_source_game_mappings m
join public.games g on g.id = m.game_id
order by lower(m.source_provider), lower(m.source_handle);

commit;
"""

sql_path.write_text(sql, encoding="utf-8")
PY

mv "$TMP_SQL" "$SQL_FILE"
echo "Generated external source game mappings seed SQL: $SQL_FILE"
