create table if not exists public.notifications (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.users(id) on delete cascade,
    actor_user_id uuid not null references public.users(id) on delete cascade,
    post_id uuid references public.posts(id) on delete cascade,
    comment_id uuid references public.comments(id) on delete cascade,
    type text not null,
    created_at timestamp without time zone default now(),
    read boolean not null default false,
    constraint notifications_target_check
        check (post_id is not null or comment_id is not null)
);

create index if not exists notifications_user_created_at_idx
    on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_read_created_at_idx
    on public.notifications (user_id, read, created_at desc);

create or replace function public.create_notifications_for_comment()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    post_owner_id uuid;
    parent_comment_owner_id uuid;
begin
    select p.author_id
      into post_owner_id
      from public.posts p
     where p.id = new.post_id;

    if post_owner_id is not null
       and post_owner_id <> new.user_id then
        insert into public.notifications (
            user_id,
            actor_user_id,
            post_id,
            comment_id,
            type
        ) values (
            post_owner_id,
            new.user_id,
            new.post_id,
            new.id,
            'post_comment'
        );
    end if;

    if new.parent_comment_id is not null then
        select c.user_id
          into parent_comment_owner_id
          from public.comments c
         where c.id = new.parent_comment_id;

        if parent_comment_owner_id is not null
           and parent_comment_owner_id <> new.user_id
           and parent_comment_owner_id is distinct from post_owner_id then
            insert into public.notifications (
                user_id,
                actor_user_id,
                post_id,
                comment_id,
                type
            ) values (
                parent_comment_owner_id,
                new.user_id,
                new.post_id,
                new.id,
                'comment_reply'
            );
        end if;
    end if;

    return new;
end;
$$;

drop trigger if exists comment_insert_notifications_trigger on public.comments;

create trigger comment_insert_notifications_trigger
after insert on public.comments
for each row
execute function public.create_notifications_for_comment();

alter table public.notifications enable row level security;

drop policy if exists "Users can view own notifications" on public.notifications;
create policy "Users can view own notifications"
on public.notifications
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can update own notifications" on public.notifications;
create policy "Users can update own notifications"
on public.notifications
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

revoke all privileges on table public.notifications from anon;
revoke all privileges on table public.notifications from authenticated;
grant select, update on table public.notifications to authenticated;

do $$
begin
    begin
        alter publication supabase_realtime add table public.notifications;
    exception
        when duplicate_object then
            null;
        when undefined_object then
            null;
    end;
end;
$$;

comment on table public.notifications is
    'User-facing notification inbox events generated by backend triggers (comments/replies, and later reactions).';

comment on function public.create_notifications_for_comment() is
    'Creates post-comment and reply notifications after comment insert while avoiding self-notifications and duplicate targets.';
